#include "../../../disk/part_uefi.h"

PARTITION_CFG const g_sprd_emmc_partition_cfg[]={
	{PARTITION_VM, 512, PARTITION_RAW},
	{PARTITION_MODEM, 10*1024, PARTITION_RAW},
	{PARTITION_DSP, 5*1024, PARTITION_RAW},
	{PARTITION_FIX_NV, 3840, PARTITION_RAW},
	{PARTITION_BACK_NV, 3840, PARTITION_RAW},
	{PARTITION_RUNTIME_NV, 3840, PARTITION_RAW},
	{PARTITION_PROD_INFO, 3840, PARTITION_RAW},
	{PARTITION_KERNEL, 10*1024, PARTITION_RAW},
	{PARTITION_SYSTEM, 250*1024, PARTITION_RAW},
	{PARTITION_LOGO, 1*1024, PARTITION_RAW},
	{PARTITION_USER_DAT, MAX_SIZE_FLAG, PARTITION_RAW},
	{PARTITION_CACHE, 20*1024, PARTITION_RAW},
	{0,0,0}
};
