#ifndef _DISK_PART_UEFI_H
#define _DISK_PART_UEFI_H

typedef enum _PARTITION_INDEX_TAG
{
	PARTITON_NULL = 0,
	PARTITION_VM,
	PARTITION_MODEM,
	PARTITION_DSP,
	PARTITION_FIX_NV1,
	PARTITION_FIX_NV2,
	PARTITION_RUNTIME_NV1,
	PARTITION_RUNTIME_NV2,
	PARTITION_PROD_INFO1,
	PARTITION_PROD_INFO2,
	PARTITION_PROD_INFO3,
	PARTITION_KERNEL,
	PARTITION_SYSTEM,	
	PARTITION_USER_DAT,
	PARTITION_CACHE,
	PARTITION_LOGO,
	PARTITION_RECOVERY,
	PARTITION_FASTBOOT_LOGO,
	PARTITION_MISC,
	PARTITION_SD,
	PARTITION_TOTAL_COUNT
}EFI_PARTITION_INDEX;

typedef enum _PARTITION_ATTR_TAG
{
	PARTITION_RAW = 0,
	PARTITION_EXT4 = 1,
	PARTITION_ATTR_COUNT
}PARTITION_ATTR_TAG;

#define MAX_PARTITION_INFO	(((PARTITION_TOTAL_COUNT + 3) / 4) * 4)

#define MAX_SIZE_FLAG	0xFFFFFFFF
typedef struct _PARTITION_CFG
{
	unsigned int partition_index;
	unsigned int partition_size;  //
	unsigned int partition_attr;
} __attribute__ ((packed)) PARTITION_CFG,*PPARTITION_CFG;


unsigned int write_uefi_parition_table(PARTITION_CFG *p_partition_cfg);

#endif	/* _DISK_PART_UEFI_H */
