

#ifndef _SDIO_CARD_PAL_H_
#define _SDIO_CARD_PAL_H_
#include "../mmc/sdhost_drv.h"
#define 	SDIO_SLAVE_FUNC_0 	(0)
#define 	SDIO_SLAVE_FUNC_1 	(1)

typedef struct SDIO_CARD_PAL_Struct{
    int flag;
    unsigned int MagicNum;            // "SDIO"
    SDHOST_HANDLE sdio_port;
    volatile unsigned int s_CardEvent;
}SDIO_CARD_PAL_Struct_T;
typedef struct SDIO_CARD_PAL_Struct* SDIO_CARD_PAL_HANDLE;



typedef enum
{
	SDIO_CARD_PAL_SLOT_0,
	SDIO_CARD_PAL_SLOT_1,
	SDIO_CARD_PAL_SLOT_2,
	SDIO_CARD_PAL_SLOT_3,
	SDIO_CARD_PAL_SLOT_MAX
}SDIO_CARD_PAL_SLOT_E;

SDIO_CARD_PAL_HANDLE SPRD_SDSlave_Pal_Open(SDIO_CARD_PAL_SLOT_E slotNo);
void SDIO_Card_Pal_SlotSelect(SDIO_CARD_PAL_SLOT_E slotNo);

typedef enum
{
	SDIO_CARD_PAL_OFF,
	SDIO_CARD_PAL_ON
}SDIO_CARD_PAL_PWR_E;
int SPRD_SDSlave_Pal_Pwr(SDIO_CARD_PAL_HANDLE handle,SDIO_CARD_PAL_PWR_E onOrOff);

typedef enum
{
	SDIO_CARD_PAL_400KHz,			// 初始化频率
	SDIO_CARD_PAL_20MHz,			// MMC卡的工作频率
	SDIO_CARD_PAL_25MHz,			// SD卡的工作频率
	SDIO_CARD_PAL_50MHz			// SD卡高速模式下的工作频率
}SDIO_CARD_PAL_CLKTYPE_E;
int SPRD_SDSlave_Pal_SetClk(SDIO_CARD_PAL_HANDLE handle,SDIO_CARD_PAL_CLKTYPE_E clkType);

typedef enum
{
	SDIO_CARD_PAL_1_BIT,
	SDIO_CARD_PAL_4_BIT,
	SDIO_CARD_PAL_8_BIT
}SDIO_CARD_PAL_BUFWIDTH_E;
int  SPRD_SDSlave_Pal_SetBusWidth(SDIO_CARD_PAL_HANDLE handle,SDIO_CARD_PAL_BUFWIDTH_E widthType);

typedef enum
{
	SDIO_CARD_PAL_LOW_SPEED,
	SDIO_CARD_PAL_HIGH_SPEED
}SDIO_CARD_PAL_SPEEDMODE_E;
int SPRD_SDSlave_Pal_SetSpeedMode(SDIO_CARD_PAL_HANDLE handle,SDIO_CARD_PAL_SPEEDMODE_E speedMode);

typedef enum
{
// cmdindex,rsp,transmode
	CARD_CMD0_GO_IDLE_STATE,
	CARD_CMD1_SEND_OP_COND, /*MMC*/
	CARD_CMD2_ALL_SEND_CID,
	CARD_CMD3_SEND_RELATIVE_ADDR, /*SD*/
	CARD_CMD3_SET_RELATIVE_ADDR, /*MMC*/
	CARD_CMD4_SET_DSR,
	CARD_CMD6_SWITCH_FUNC,
	CARD_CMD7_SELECT_DESELECT_CARD,
	CARD_CMD8_SEND_IF_COND, /*SD*/
	CARD_CMD9_SEND_CSD,
	CARD_CMD10_SEND_CID,
	CARD_CMD11_READ_DAT_UNTIL_STOP, /*MMC*/
	CARD_CMD11_READ_DAT_UNTIL_STOP_AUT12, /*MMC*/
	CARD_CMD12_STOP_TRANSMISSION,	//It is auto performed by Host
	CARD_CMD13_SEND_STATUS,
	CARD_CMD15_GO_INACTIVE_STATE,
	CARD_CMD16_SET_BLOCKLEN,
	CARD_CMD17_READ_SINGLE_BLOCK,
	CARD_CMD18_READ_MULTIPLE_BLOCK,
	CARD_CMD18_READ_MULTIPLE_BLOCK_AUT12,
	CARD_CMD20_WRITE_DAT_UNTIL_STOP, /*MMC*/	
	CARD_CMD20_WRITE_DAT_UNTIL_STOP_AUT12, /*MMC*/
	CARD_CMD23_SET_BLOCK_COUNT, /*MMC*/
	CARD_CMD24_WRITE_BLOCK,
	CARD_CMD25_WRITE_MULTIPLE_BLOCK,
	CARD_CMD25_WRITE_MULTIPLE_BLOCK_AUT12,

	CARD_CMD26_PROGRAM_CID, /*MMC*/
	CARD_CMD27_PROGRAM_CSD,
	CARD_CMD28_SET_WRITE_PROT,
	CARD_CMD29_CLR_WRITE_PROT,
	CARD_CMD30_SEND_WRITE_PROT,	// ??

	CARD_CMD32_ERASE_WR_BLK_START, /*SD*/
	CARD_CMD33_ERASE_WR_BLK_END, /*SD*/

	CARD_CMD35_ERASE_GROUP_START, /*MMC*/
	CARD_CMD36_ERASE_GROUP_END, /*MMC*/

	CARD_CMD38_ERASE,

	CARD_CMD39_FAST_IO, /*MMC*/
	CARD_CMD40_GO_IRQ_STATE, /*MMC*/

	CARD_CMD42_LOCK_UNLOCK_SD, /*SD*/	// ??
	CARD_CMD42_LOCK_UNLOCK_MMC, /*MMC*/	// ??
	CARD_CMD55_APP_CMD,
	CARD_CMD56_GEN_CMD_SD, /*SD*/	//??
	CARD_CMD56_GEN_CMD_MMC, /*MMC*/	//??


	CARD_ACMD6_SET_BUS_WIDTH,	 /*SD*/
	CARD_ACMD13_SD_STATUS, /*SD*/
	CARD_ACMD22_SEND_NUM_WR_BLCOKS, /*SD*/
	CARD_ACMD23_SET_WR_BLK_ERASE_COUNT, /*SD*/
	CARD_ACMD41_SD_SEND_OP_COND, /*SD*/
	CARD_ACMD42_SET_CLR_CARD_DETECT, /*SD*/
	CARD_ACMD51_SEND_SCR, /*SD*/


#if defined(SPRD_SUPPORT_MCEX)
	CARD_CMD34_READ_SEC_CMD,
	CARD_CMD35_WRITE_SEC_CMD,
	CARD_CMD36_SEND_PSI,
	CARD_CMD37_CTL_TRM,
#endif

	CARD_CMDMAX
}SDIO_CARD_PAL_CMD_E;

typedef struct CARD_DATA_PARAM_TAG
{
	unsigned char *databuf;	// the buffer address ,that data will be stored in or  read from
	unsigned int blkLen;	// block size
	unsigned int blkNum;	// block number
}
CARD_DATA_PARAM_T;

typedef enum
{
	SDIO_CARD_PAL_ERR_NONE			= 0,
	SDIO_CARD_PAL_ERR_RSP			= BIT_0,
	SDIO_CARD_PAL_ERR_CMD12			= BIT_1,
	SDIO_CARD_PAL_ERR_CUR_LIMIT		= BIT_2,
	SDIO_CARD_PAL_ERR_DATA_END		= BIT_3,
	SDIO_CARD_PAL_ERR_DATA_CRC		= BIT_4,
	SDIO_CARD_PAL_ERR_DATA_TIMEOUT		= BIT_5,
	SDIO_CARD_PAL_ERR_CMD_INDEX		= BIT_6,
	SDIO_CARD_PAL_ERR_CMD_END		= BIT_7,
	SDIO_CARD_PAL_ERR_CMD_CRC		= BIT_8,
	SDIO_CARD_PAL_ERR_CMD_TIMEOUT		= BIT_9
}SDIO_CARD_PAL_ERROR_E;


typedef enum
{
// cmdindex,rsp,transmode
    SDIO_CMD3_SEND_RELATIVE_ADDR,
    SDIO_CMD5_SEND_OP_COND, 
    SDIO_CMD7_SELECT_DESELECT_CARD,
    SDIO_CMD52_IO_RW_DIRECT,
    //SDIO_CMD52_IO_RW_DIRECT_ABORT,
    //SDIO_CMD52_READ_BLOCKS_SUSPEND,
    //SDIO_CMD52_READ_BLOCKS_RESUME,
    //SDIO_CMD52_WRITE_BLOCKS_SUSPEND,
    //SDIO_CMD52_WRITE_BLOCKS_RESUME,
    SDIO_CMD53_READ_BYTES,
    SDIO_CMD53_READ_BLOCKS,
    //SDIO_CMD53_READ_BLOCKS_NO_TRANS_COMP,
    //SDIO_CMD53_READ_BLOCKS_RESUME,
    //SDIO_CMD53_READ_BLOCKS_INFINITE,
    SDIO_CMD53_WRITE_BYTES,
    SDIO_CMD53_WRITE_BLOCKS,
    //SDIO_CMD53_WRITE_BLOCKS_NO_TRANS_COMP,
    //SDIO_CMD53_WRITE_BLOCKS_RESUME,
    //SDIO_CMD53_WRITE_BLOCKS_INFINITE,
    SDIO_CMDMAX
}SDIO_MASTER_PAL_CMD_E;

SDIO_CARD_PAL_ERROR_E SPRD_SDSlave_Pal_SendCmd(
    /*IN*/SDIO_CARD_PAL_HANDLE handle,
    /*IN*/SDIO_MASTER_PAL_CMD_E cmd,
    /*IN*/unsigned int argument,
    /*IN*/CARD_DATA_PARAM_T* dataParam,
    /*OUT*/unsigned char* rspBuf
);
int SPRD_SDSlave_Pal_Close(SDIO_CARD_PAL_HANDLE handle);

typedef enum CARD_VERTION_E_TAG{
	CARD_V_UNKONWN,
	CARD_SD_V1_X,
	CARD_SD_V2_0_STANDARD,
	CARD_SD_V2_0_HIGHCAP,
	CARD_MMC_331
}CARD_VERTION_E;

typedef struct CARD_PORT_TAG{
	int open_flag;

	SDIO_CARD_PAL_HANDLE sdioPalHd;

	CARD_VERTION_E vertion;
	unsigned short RCA;
	SDIO_CARD_PAL_BUFWIDTH_E bus_width;

	unsigned int ClockRate;
	unsigned int BlockLen[2];

	unsigned int Nac_Max;
	unsigned int GrpSize;
	unsigned int Capacity;

	unsigned short  CCC;
	int ifSupportEC;
	int ifSupportHighSpeed;

	int ifEnterEC;
	int ifEnterHighSpeed;
}CARD_PORT_T;
typedef struct CARD_PORT_TAG* CARD_SDIO_HANDLE;
#endif



